services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api/Dockerfile
    env_file: .env.dev
    volumes: [".:/app"]
    ports: ["8080:8080"]
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on: [db, redis, qdrant]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aqacs
    ports: ["5433:5433"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: ["/Users/amoghagadde/Desktop/Amogha/BulkMagic/Compliance_Tool/qdrant-storage:/qdrant/storage"]
